### ISSUE TITLE
Having a couple of errors once I imported HMD-Eyes in Unity

### ISSUE THREAD

**Issue by AyaAbdulnasser** [pupil-labs/hmd-eyes#114]
I am using Quest pro to track and get eye features like pupil, fixation, and position. However, I downloaded hmd-eyes, and I received a bunch of errors. May I know how I could solve this problem?
Is the hmd-eyes asset the proper asset to be used for quest pro as well?

![ERRORS1](https://user-images.githubusercontent.com/121787161/210202468-6908666d-2cc9-47a7-adc4-6a30414c295e.PNG)

**Comment by papr** [comment]
Hi!

Hmd-eyes is agnostic to your VR hardware, i.e. it should work with the quest pro quite fine.

Please see the [`Dependencies` section in the repository's README](https://github.com/pupil-labs/hmd-eyes#develop-integrate-and-extend) for a possible solution to your issue.

**Comment by AyaAbdulnasser** [comment]
Thank you so much. I appreciate your response. It helped me out ^^.

**Comment by papr** [comment]
Great! Good luck with your project!

**Comment by eioe** [comment]
Hey @AyaAbdulnasser , sorry for hijacking this thread. 
I'd be curious though how and why you are using Pupil Labs solutions with the Quest Pro (instead of the inbuilt eye tracking). Is it because Pupil Labs offers more data (e.g., higher frame rate and access to raw data, etc)? Did you make a comparison in terms of reliability and accuracy between the two tracking systems? 
On the technical side: how did you mount the Pupil Labs eye cameras in the Quest Pro? Did you build a custom setup? 
I'd be very thankful for some insights which I think will also be of interest to the community. If you prefer, you can of course also contact me directly (email is in my GH profile). 
Thx & many greetings!
