### ISSUE TITLE
Can't get Unity EyeGaze Value

### ISSUE THREAD

**Issue by loolsasy** [pupil-labs/hmd-eyes#40]
I add unity_pupil_plugin_vr and play Calibration scene

but PupilGazeTracker can't get PupilData._2D.GetEyeGaze

That value is always (0,0)

How do I get eye gaze and eye position?

**Comment by AndreNicolai** [comment]
This should only be the case if you are not receiving any positional data. Did the calibration go through, successfully? 

Please give a little more information on your setup to help us debug the situation.
Do you track one or two eyes?
Are the values for both zero?
Which version of Pupil Capture/Service are you using?

If possible, please also try the "Blink" Unity demo scene. It does not require you to go through a calibration to see if the communication itself is working properly.

**Comment by loolsasy** [comment]
Thanks response.
I use pupil_v1.2.7_windows_x64 file and windows10
pupil_capture_windows_x64_v1.2.7 and pupil_service_windows_x64_v1.1.2 in pupil_v1.2.7_windows_x64 version
[https://github.com/pupil-labs/pupil/releases](url)


I want two eye track 

If I play Calibration scene, open two pupilCapture But they are not same time playing.
If left capture play - right capture is stoped and right capture play - left capture is stoped

And I get data in Connection.cs - InitializeSubscriptionSocket()
topic, norm_pos(one position), confidence, timestamp, base_data..etc

But maked norm_pos key maked norm_pos_  in PupilTools.cs - UpdateGaze()
I thank stringForEyeID() return null

If norm_pos key set norm_pos_1 in PupilTools.cs - UpdateGaze()

Change Left Eye in PupilGazeTracker.cs
`	void OnGUI ()
    {
#if !UNITY_WSA
		if (!isOperatorMonitor)
		{
			string str = "Capture Rate=" + FPS;
			str += "\nLeft Eye:" + PupilData._2D.GetEyeGaze(GazeSource.LeftEye).ToString ();
			str += "\nRight Eye:" + PupilData._2D.GetEyeGaze(GazeSource.RightEye).ToString ();
			GUI.TextArea (new Rect (50, 50, 200, 50), str);
		}
#endif
	}`

I think, my problem is how get two eye data and get value stringForEyeID() funtion

**Comment by AndreNicolai** [comment]
Okay,
from your description it sounds like both eye cameras are set to the same eye ID.
So if one is accessing the ID, the second eye window is blocked.

For now, I would recommend the following:
On a freshly started computer, please open Pupil Capture directly through the executable.
In the main GUI, in the "General Settings" menu on the right, click the "Restart with default settings" button.
Once the GUI window has re-opened, it should also open one eye (ID 0).
Again in the "General Settings" menu, select "Detect eye 1" so that there should now be two windows open.
Check, whether both eye cameras are reacting.
If this is not working, I suspect something is broken hardware-wise.
If it is working fine, start Unity, load the VR project and play the Calibration.
If this is not working, I propose we do a remote session so I can have a look at it.

**Comment by loolsasy** [comment]
Thank you.
Now They are working for unity!!

**Comment by AndreNicolai** [comment]
Can you describe, what fixed the problem for you?
It might help others avoid it and point us to what should be better documented.

**Comment by loolsasy** [comment]
There were a lot of problems.
First, it seems that communication was not normally done.
When BlinkScene was executed, the Blink detected log was not output normally.
Secondly, there were two pupil_services running, but one was stopped and the other was running alternately.
Third, the value of stringForEyeID () in the UpdateGaze () function in pupilTools.cs is null.
When I check the log, the value of isID is false and it is null.
Now all three of these problems work fine, but ...
I do not know why.
Just log it, check which part is the problem, give Pupil_capture "Restart with default settings" and change PupilGazeTracker's path from pupil_service to pupil_capture.
I hope this process will help those who have experienced the same problems as myself.

**Comment by AndreNicolai** [comment]
I think the problem originated in the version of Pupil Service that came with the 1.2.7 release. 
Once you switched to Pupil Capture, everything seemed to work fine.
There is a known bug with Service 1.2.7 that is fixed in the newest release, but for now I would recommend staying with Pupil Capture.
