### ISSUE TITLE
Accessing "gaze" Data

### ISSUE THREAD

**Issue by BerndtSam** [pupil-labs/hmd-eyes#51]
I'm having trouble accessing the "gaze" data on my own unity application using the Pupil Labs Unity plugin.

For calibration I am using the pupil manager prefab with an added "WorldCamera" that starts as activated, is deactivated on calibration start up, then reactivated again after calibration is successful.

After the calibration procedure, I deactivate the calibration camera and activate the "WorldCamera." After doing such, I set the following lines of code:

```
PupilSettings.Instance.currentCamera = Camera.main; // I confirmed this is the camera I want it to be
PupilTools.IsGazing = true;
PupilTools.SubscribeTo("gaze");
```

After reading the [documentation](https://github.com/pupil-labs/hmd-eyes/blob/master/Developer.md) I expected the code in the function InitializeSubscriptionSocket of connection.cs to be called every time the hardware detects a gaze:

```
subscriptionSocketForTopic[topic].ReceiveReady += (s, a) => 
{
int i = 0;
NetMQMessage m = new NetMQMessage();
while(a.Socket.TryReceiveMultipartMessage(ref m)) {
...
switch(msgType) {
...
case "gaze":
case "pupil.0":
case "pupil.1":
	var dictionary = MessagePackSerializer.Deserialize<Dictionary<string,object>> (mStream);
...
        if (confidence > 0.6f && msgType == "gaze")
                                PupilTools.gazeDictionary = dictionary;
...
```

Such that when I call `PupilData._2D.GazePosition` or `PupilData._3D.GazePosition` I would receive meaningful data. 

However, after the calibration function ends the subscriptionsocket is never called. I suspect this isn't just for the gaze subscription either.

My suspicion is that something got deactivated which makes the subsciptions void. However, I have yet to prove this.

Any suggestions?

**Comment by cboulay** [comment]
The following commit changed the pupil message topic from "gaze" to "gaze.2d.0" (or .1): https://github.com/pupil-labs/pupil/commit/5b5a5c32101ab6435992daecbcfdef758e3a9983

This was then changed again from .0/.1 etc to .0./.1. etc here: https://github.com/pupil-labs/pupil/commit/991633586b1decf840b71a11ac9aee7f3faf00b8

Even since the first change in Dec 2017, hmd-eyes has not caught up and it still looks for the "gaze" topic here: https://github.com/pupil-labs/hmd-eyes/blob/master/unity_pupil_plugin_vr/Assets/pupil_plugin/Scripts/Networking/Connection.cs#L165

We've modified that code to also look for the new topics, and now we are catching events, but the resulting tracking feels off. We can prepare a pull request with our minimal changes so far but I'm afraid that we missed something else that has changed in either the message format or the content.
