### ISSUE TITLE
Not compileable on UWP?

### ISSUE THREAD

**Issue by Yolo-Jerome** [pupil-labs/hmd-eyes#57]
I get compiler errors after switching the platform to UWP. Since I'm going to deplay to the Holo-Lens, I imported the MixedRealityToolkit and switched the plattform to UWP.

![2018-11-25_2142](https://user-images.githubusercontent.com/23453548/48984379-200d4c00-f0fb-11e8-8b68-d6377b28c89c.png)

right after switching I see the following error in the console:

![2018-11-25_2144](https://user-images.githubusercontent.com/23453548/48984387-43d09200-f0fb-11e8-92f9-cf4fb55e1045.png)

so I tried to fix that but simply doing

```
public class Heatmap : MonoBehaviour 
{
#if !UNITY_WSA
    //  ...
#endif
}
```

but now I see there is even more

![2018-11-25_2147](https://user-images.githubusercontent.com/23453548/48984454-159f8200-f0fc-11e8-8707-8a40c68d6a58.png)

---

Am I doing something wrong or is pupil-labs currently not compatible with UWP?

---

**Update**

It worked now using the `Pupil.Import.Package.HoloLens.unitypackage` from `v0.5.1` is it supposed to be like that?

**Comment by jdpoenisch** [comment]
Update (from my personal account): I just retried it with the newest 
[Pupil.Import.Package.VR.v0.61.unitypackage](https://github.com/pupil-labs/hmd-eyes/releases/tag/v0.61)
but I still get exactly the same exception.

I can see that `FFmpegPipe` and actually the entire namespace `FFmpegOut` is commented out 

    #if !Unity_WSA
    // ...
    #endif

but as far as I know the MixedRealityToolkit requires to be on Windows Universal UWP in order to work.


What do I have to do in order to use Pupil-Labs with the HoloLens?
I need it for my master thesis :)

**Comment by fx-lange** [comment]
hi @jdpoenisch,

yes the `*.VR.package` is not compileable with UWP - you need the HoloLens package.
[0.5.1](https://github.com/pupil-labs/hmd-eyes/tree/v0.5.1) is indeed the last release where the `*.HoloLens.unitypackage` was included. I will look into it for the next release but in the meantime I would recommend sticking to `0.5.1` which should work for 2D gaze estimations.

**Comment by jdpoenisch** [comment]
Oh ok, thanks for the feedback!

I was a bit confused how to use the packages. I actually thought I would have to have the "Pupil.Import.Package.VR.unitypackage" **+** the "Pupil.Import.Package.HoloLens.unitypackage" on top of it like kind of a patch. ^^

**Comment by fx-lange** [comment]
@jdpoenisch you are welcome and thanks for the feedback.
