### ISSUE TITLE
Blink not working

### ISSUE THREAD

**Issue by patryk191129** [pupil-labs/hmd-eyes#66]
In reference of this issue [https://github.com/pupil-labs/hmd-eyes/issues/53](https://github.com/pupil-labs/hmd-eyes/issues/53). I'm using HMD-eyes 0.63 and PupilService 1.10.20 and It's still unable to detect blinks. I've used debug to print all received messages and I've got only these data: **gaze.2d.0** and **gaze.2d.1**. Even BlinkDemo Default Scene can't detect any blinks.

**Comment by fx-lange** [comment]
Hi @patryk191129,

thanks for your report. Could you please try hmd-eyes together with the newest pupil capture version instead of pupil service - just for testing. Could you please check if the blink detection plugin is running in Pupil Capture after starting the blink demo in Unity. 
For the blink demo it is important to have a solid pupil detection, you can check the confidence in Pupil Capture.

**Comment by patryk191129** [comment]
With Pupil Capture software it detects blinks, thanks a lot :), I would suggest to change in README.md to prevent future misunderstands ;)
_3. Start Pupil Service via the pupil_service.exe in the Pupil Service App folder._
to
3. _Start Pupil Capture via the pupil_capture.exe in the Pupil Capture App folder._

Now, I've got next trouble, how to determine opened/closed eye via blink event, because it's sending message only when I blink, but not working when got still closed eye.

**Comment by fx-lange** [comment]
Hi @patryk191129, 
thanks for the feedback. Blink should also work with Pupil Service but it is harder to set it up and debug it without the GUI provided by Pupil Capture.

We changed the README and documented the differences between Capture and Service for hmd-eyes.
